### ISSUE TITLE
Error Message: Unable to read rom file

### ISSUE THREAD

**Issue by alebersol** [Eagleheardt/EWingIPSPatcher#3]
I have tried using several ROM images and all have returned an error message.
Do you have any suggestions?

**Comment by Eagleheardt** [comment]
Make sure that Python3 as well as TKinter libraries are installed.
Then, set the EWingPatcher.py to be an executable file.
Execute EWingPatcher.py directly and a graphical user interface should pop up for you

**Comment by alebersol** [comment]
I have tried all these

**Comment by Eagleheardt** [comment]
Does it do this for every ROM image?
Are you only trying to apply an IPS type patch?
What distro of Linux are you running? Is everything up to date?

**Comment by alebersol** [comment]
I've invoked it in a terminal and it gave the following error message : 
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python3.6/tkinter/__init__.py", line 1702, in __call__
    return self.func(*args)
  File "EWingPatcher.py", line 294, in btnROMClick
    checkROM(fullROMPath.get())
  File "EWingPatcher.py", line 173, in checkROM
    checkROMIO.close() # closes the file
UnboundLocalError: local variable 'checkROMIO' referenced before assignment

And the error box Unable to read rom file

Python: 3.6.5-3
Tkinter: 3.6.5-3

Tried with Genesis Mortal Kombat 2, either GEN or BIN, to the same results.

Can you suggest another ROM file?

Regards,

**Comment by Eagleheardt** [comment]
I would suggest Super Mario Bros. 1 as a ROM
try deleteing your copy of the program and re download it

**Comment by Eagleheardt** [comment]
Are you still receiving this error?

**Comment by alebersol** [comment]
I have not tested this again, yet

**Comment by Eagleheardt** [comment]
Could you also please provide your linux distro?
In addition, if you are still experiencing this error, please submit an album of screenshots, one at each small step, so that I can watch your error unfold.

**Comment by alebersol** [comment]
My distro is PCLinuxOS, RPM based.
Tried to patch 1942 NES to the same results.
![Captura de tela de 2019-11-12 23:41:12](https://user-images.githubusercontent.com/19739387/68728967-77742880-05a7-11ea-81c4-d9b575f50dcb.png)
![Captura de tela de 2019-11-12 23:42:16](https://user-images.githubusercontent.com/19739387/68728975-7ba04600-05a7-11ea-8e0b-98e4c5331ba0.png)
![Captura de tela de 2019-11-12 23:42:35](https://user-images.githubusercontent.com/19739387/68729037-af7b6b80-05a7-11ea-98bf-51fdd5af9df0.png)
![Captura de tela de 2019-11-12 23:42:57](https://user-images.githubusercontent.com/19739387/68729042-b3a78900-05a7-11ea-8dfd-9ab88aae440f.png)

Tried another IPS patcher, sadly windows based, just to test the NES rom patching, and it worked.

**Comment by alebersol** [comment]
OHHHHH MY GOD!!!

The rom files were read-only. I changed their permissions and it **WORKED**
I'm going to package it to my distro.
What Icon should I use ???
Thanks for the support, quick response,  and I'm extremely sorry for this problem.

**Comment by Eagleheardt** [comment]
I wouldn't be at all mad if you used my 'EWing' icon I made for RHDN: https://www.romhacking.net/community/images/4405image.png

I'm glad we could resolve this, as I could not figure out why you would be getting that error!

**Comment by alebersol** [comment]
Well, I had the same problem with Lazy_Ips, and, the same solution, so, it was a file permission issue.
Going to package it.
Thanks for the quick response and support. 
Regards,

**Comment by alebersol** [comment]
Done, packaged for PCLinuxOS.
Thanks for your support.

Best regards,

**Comment by alebersol** [comment]
![screen_cap](https://user-images.githubusercontent.com/19739387/69457601-2ead3400-0d4c-11ea-852b-39ee7445bd8f.png)
